# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   tapioca generate

# typed: strong

module Coffee
end

module Coffee::Rails
end

class Coffee::Rails::Engine < ::Rails::Engine
end

module Coffee::Rails::JsHook
  extend(::ActiveSupport::Concern)
end

class Coffee::Rails::TemplateHandler
  def self.call(template, source = _); end
  def self.erb_handler; end
end

Coffee::Rails::VERSION = T.let(T.unsafe(nil), String)
