# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   tapioca generate

# typed: strong

module CoffeeScript
  def self.compile(script, options = _); end
  def self.engine; end
  def self.engine=(engine); end
  def self.version; end
end

CoffeeScript::CompilationError = ExecJS::ProgramError

CoffeeScript::EngineError = ExecJS::RuntimeError

CoffeeScript::Error = ExecJS::Error

module CoffeeScript::Source
  def self.bare_option; end
  def self.bundled_path; end
  def self.contents; end
  def self.context; end
  def self.path; end
  def self.path=(path); end
  def self.version; end
end

CoffeeScript::Source::COMPILE_FUNCTION_SOURCE = T.let(T.unsafe(nil), String)
