# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   tapioca generate

# typed: true

module Spring
  def self.after_fork(&block); end
  def self.after_fork_callbacks; end
  def self.application_root; end
  def self.application_root=(_); end
  def self.application_root_path; end
  def self.gemfile; end
  def self.project_root_path; end
  def self.quiet; end
  def self.quiet=(_); end
  def self.verify_environment; end
  def self.watch(*items); end
  def self.watch_interval; end
  def self.watch_interval=(_); end
  def self.watch_method; end
  def self.watch_method=(method); end
  def self.watcher; end
  def self.watcher=(_); end
end

module Spring::Watcher
end

class Spring::Watcher::Listen < ::Spring::Watcher::Abstract
  def base_directories; end
  def changed(modified, added, removed); end
  def listener; end
  def start; end
  def stop; end
  def subjects_changed; end
  def watching?(file); end
end
